name: chat_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # State Management
  get: ^4.1.4
  # storage
  get_storage:
  # working with dates
  intl: ^0.17.0
  # images from gallery   ios not added
  images_picker: ^1.0.0
  # toast
  fluttertoast: ^7.1.6
  # search view
  material_floating_search_bar:
#  images
  cached_network_image:
#  check network
  data_connection_checker:
# menu
  searchable_dropdown: ^1.1.3
#  Firebase ios not added
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.5
  firebase_storage: ^8.0.3
  firebase_messaging: ^9.0.1
  flutter_local_notifications: ^5.0.0
  flutter_ringtone_player: ^2.0.0
#  animation
  animate_do: ^2.0.0
#  emoji
  emoji_picker: ^0.1.0
  shared_preferences:
#  message background view
  bubble: ^1.2.1
#  zoomable image
  photo_view: ^0.11.1
#   text allows links
  flutter_linkify:
    git:
      url: https://github.com/MohamedEL-Torky/flutter_linkify
#   video
  flick_video_player: ^0.2.0
#  view slider
  carousel_slider:
#  urls
  url_launcher:
#  swipe to reply messages
  swipe_to: ^0.0.1+6
#  sound player
  audioplayers: ^0.18.3
#  network
  dio: ^4.0.0
#  icon
  flutter_launcher_icons:
#  splash screen    see more in dev section
  splash_screen_view:
#  keyboard
  keyboard_visibility: ^0.5.6
#  translation library
  translator: ^0.1.7





dev_dependencies:
  flutter_test:
    sdk: flutter

  #native splash screens
  flutter_native_splash:

flutter_native_splash:
  color: "#FFFFFF"
  image: src/images/splash_logo.png
  #  background_image: "src/images/splash_bg.png"
  android: true
  ios: true
  #  android_gravity: fill
  #  ios_content_mode: scaleAspectFill

  # run this command
  #  flutter pub run flutter_native_splash:create



flutter_icons:
  android: true
  ios: true
  image_path: "src/images/logo.png"
#  run this
#  flutter pub run flutter_launcher_icons:main


flutter:
  uses-material-design: true

  assets:
    - src/images/
    - src/images/flags/
    - src/json/
    - src/sounds/
